### ISSUE TITLE
Time bar

### ISSUE THREAD

**Issue by jefffhaynes** [jefffhaynes/LaunchPad2#1]
I have finally gotten to the point where I have enough tracks to start scrolling vertically.  An issue that has surfaced is that the time indicator row at the top and the restricted area row at the top both scroll off the top of the screen with the earlier tracks.  They should stay on the screen with the headers.  As usual I can work around this, but wanted to make you aware.

**Comment by bobwaldman** [comment]
Medium priority.  Can work around, but making things line up just right is trickier.

**Comment by jefffhaynes** [comment]
I believe this is fixed now, but please reopen if not.
