### ISSUE TITLE
Make beats creation a separate activity

### ISSUE THREAD

**Issue by bobwaldman** [jefffhaynes/LaunchPad2#7]
For a full show, the beats creation take a bit over 3 minutes.  During those 3 minutes the software is very slow and pokey as that runs in the background.  I find I wait the full 3 minutes before I start work.

If I am correct, the beats track is only needed when creating automated music, which is done early in show creation and then not used again.  So it serves no purpose for the bulk of the software runs which are done after the lighting has been finalized.

Can we make the beats track creation not an automated part of the data file load?  In other words the music gets loaded and we are ready to go.  If this is a run where we will do automated music creation, then we click an icon at the top (to the right of <save as>?) and that would load the beat track.  Thus we spend the 3 minutes only when necessary.

This would be great to do, if I understand it all correctly.

**Comment by jefffhaynes** [comment]
Fixed in new version
