### ISSUE TITLE
Alphabetize Node List

### ISSUE THREAD

**Issue by bobwaldman** [jefffhaynes/LaunchPad2#8]
It would be helpful when clicking on the network button if the list of nodes were alphabetical.  This will help during final checks just before show time.

Also, when setting up the node port assignments, by clicking on a track and then assigning a node/port, it would be helpful if the nodes were also sorted alphabetically.  The ports are already sorting properly.  It would make the assigning of nodes much faster and less error-prone.

Neither of these are high priority - they are nice-to-haves, and easily worked around as necessary.

**Comment by jefffhaynes** [comment]
Fixed in new version
